# Generated by Django 5.1.4 on 2025-04-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0002_alter_sales_photo_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_status',
            field=models.CharField(choices=[('Действующая', 'Действующая'), ('Закрытая', 'Закрытая')], default='Действующая', max_length=30, verbose_name='Статус точки'),
        ),
    ]
