# Generated by Django 5.1.4 on 2026-09-22 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tph_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Дата отчёта')),
                ('photo', models.ImageField(upload_to='report_ocr/uploads/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Обрабатывается'), ('done', 'Готово'), ('error', 'Ошибка распознавания')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_uploads', to='tph_system.store')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50)),
                ('field_name', models.CharField(max_length=100)),
                ('sub_field', models.CharField(blank=True, max_length=20)),
                ('extracted_value', models.CharField(blank=True, max_length=50)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('system_value', models.CharField(blank=True, max_length=50)),
                ('is_match', models.BooleanField(null=True)),
                ('confirmed_value', models.CharField(blank=True, max_length=50)),
                ('reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('crop_image', models.ImageField(blank=True, help_text='Вырезанная ячейка — нужна и для ревью, и как сэмпл для дообучения', upload_to='report_ocr/crops/%Y/%m/%d/')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='report_ocr.reportupload')),
            ],
            options={
                'ordering': ['upload', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='reportupload',
            constraint=models.UniqueConstraint(fields=('location', 'report_date'), name='uniq_report_per_location_date'),
        ),
        migrations.AddIndex(
            model_name='fieldresult',
            index=models.Index(fields=['upload', 'section'], name='report_ocr__upload__e96bb7_idx'),
        ),
    ]
