# Generated by Django 5.1.4 on 2024-12-10 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinStatsMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Отчетный месяц')),
                ('revenue', models.IntegerField(verbose_name='Выручка (Кассы)')),
                ('salaries', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Зарплаты')),
                ('expenses', models.IntegerField(default=0, verbose_name='Расходы')),
                ('profit', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Прибыль')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user_edited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено')),
            ],
            options={
                'verbose_name': 'Финансы - компания',
                'verbose_name_plural': 'Финансы - компания',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ImplEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50, verbose_name='Тип события')),
                ('event_message', models.TextField(verbose_name='Текст события')),
                ('status', models.CharField(choices=[('Системная ошибка', 'Системная ошибка'), ('Бизнес ошибка', 'Бизнес ошибка'), ('Успешно', 'Успешно'), ('Удаление записи', 'Удаление записи')], max_length=50, verbose_name='Статус')),
                ('solved', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10, null=True, verbose_name='Решено')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user_edited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено')),
            ],
            options={
                'verbose_name': 'Системные события',
                'verbose_name_plural': 'Системные события',
                'ordering': ['-id', 'event_type'],
            },
        ),
        migrations.CreateModel(
            name='RefsAndTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.TextField(verbose_name='Информация')),
                ('refs', models.CharField(max_length=200, verbose_name='Ссылки')),
                ('date_upd', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user_edited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено')),
            ],
            options={
                'verbose_name': 'Инфо и ссылки',
                'verbose_name_plural': 'Инфо и ссылки',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('sale_type', models.CharField(choices=[('Email (фото)', 'Email (фото)'), ('Email (все)', 'Email (все)'), ('Вин. магн.', 'Вин. магн.'), ('Ср. магн.', 'Ср. магн.'), ('Бол. магн.', 'Бол. магн.'), ('Печать 10x15', 'Печать 10x15'), ('Печать 15x20', 'Печать 15x20'), ('Печать A4', 'Печать A4'), ('Заказной фотосет', 'Заказной фотосет'), ('Заказ выездной', 'Заказ выездной')], default='', max_length=40, verbose_name='Тип продажи')),
                ('photo_count', models.IntegerField(verbose_name='Кол-во фотографий')),
                ('payment_type', models.CharField(choices=[('Наличные', 'Наличные'), ('Карта', 'Карта'), ('Оплата по QR коду', 'Оплата по QR коду'), ('Перевод по номеру телефона', 'Перевод по номеру телефона'), ('Предоплаченный заказ', 'Предоплаченный заказ')], default='', max_length=40, verbose_name='Способ оплаты')),
                ('sum', models.IntegerField(verbose_name='Сумма')),
                ('cl_email', models.CharField(blank=True, max_length=40, verbose_name='Email клиента')),
                ('cl_phone', models.CharField(blank=True, max_length=12, verbose_name='Телефон клиента')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_upd', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user_edited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено')),
            ],
            options={
                'verbose_name': 'Продажи',
                'verbose_name_plural': 'Продажи',
                'ordering': ['-date_created', 'store'],
            },
        ),
        migrations.CreateModel(
            name='ConsumablesSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumable', models.CharField(max_length=60)),
                ('count', models.IntegerField()),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('user_edited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.sales')),
            ],
            options={
                'verbose_name': 'Потраченные расходники за продажу',
                'verbose_name_plural': 'Потраченные расходники за продажу',
                'ordering': ['sale'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_f_name', models.TextField(verbose_name='Описание')),
                ('param', models.CharField(max_length=50, verbose_name='Параметр')),
                ('value', models.CharField(max_length=30, verbose_name='Значение')),
                ('date_upd', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user_edited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
                'ordering': ['param'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('o_name', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('date_empl', models.DateField(verbose_name='Дата найма')),
                ('date_dism', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('date_upd', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('st_username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Учетная запись')),
                ('user_edited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_user_edited', to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено')),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['name', 'f_name'],
            },
        ),
        migrations.AddField(
            model_name='sales',
            name='photographer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='sale_photographer', to='tph_system.staff', verbose_name='Фотограф'),
        ),
        migrations.AddField(
            model_name='sales',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.staff', verbose_name='Администратор'),
        ),
        migrations.CreateModel(
            name='SalaryWeekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_begin', models.DateField(verbose_name='Начало периода')),
                ('week_end', models.DateField(verbose_name='Конец периода')),
                ('cash_box_week', models.IntegerField(default=0, verbose_name='Касса за неделю')),
                ('salary_sum', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Зарплата за неделю')),
                ('cash_withdrawn', models.IntegerField(verbose_name='Забрали наличными за неделю')),
                ('to_pay', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Осталось выплатить')),
                ('paid_out', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=10, verbose_name='Выплачено')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user_edited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.staff', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Зарплаты за неделю',
                'verbose_name_plural': 'Зарплаты за неделю',
                'ordering': ['-week_begin', 'staff'],
            },
        ),
        migrations.CreateModel(
            name='FinStatsStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Отчетный месяц')),
                ('cash_box', models.IntegerField(verbose_name='Касса')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Зарплата')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user_edited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.staff', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Финансы - сотрудники',
                'verbose_name_plural': 'Финансы - сотрудники',
                'ordering': ['-date', 'staff'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('short_name', models.CharField(max_length=20, verbose_name='Функциональное название (не изменять)')),
                ('date_upd', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user_edited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено')),
            ],
            options={
                'verbose_name': 'Точки',
                'verbose_name_plural': 'Точки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Роль не указана', 'Роль не указана'), ('Администратор', 'Администратор'), ('Фотограф', 'Фотограф'), ('Универсальный фотограф', 'Универсальный фотограф')], default='Роль не указана', max_length=40, verbose_name='Роль')),
                ('date', models.DateField(verbose_name='Дата')),
                ('date_upd', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user_edited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.staff', verbose_name='Сотрудник')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.store', verbose_name='Точка')),
            ],
            options={
                'verbose_name': 'График сотрудников',
                'verbose_name_plural': 'График сотрудников',
                'ordering': ['-date', 'store'],
            },
        ),
        migrations.AddField(
            model_name='sales',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.store', verbose_name='Точка'),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('salary_sum', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Зарплата за день')),
                ('cash_box', models.IntegerField(default=0, verbose_name='Касса за день')),
                ('date_upd', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user_edited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.staff', verbose_name='Сотрудник')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.store', verbose_name='Точка')),
            ],
            options={
                'verbose_name': 'Зарплаты',
                'verbose_name_plural': 'Зарплаты',
                'ordering': ['-date', 'staff'],
            },
        ),
        migrations.CreateModel(
            name='ConsumablesStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumable', models.CharField(max_length=60, verbose_name='Расходник')),
                ('cons_short', models.CharField(blank=True, default='', max_length=40, verbose_name='Функциональное наименование (не изменять)')),
                ('count', models.IntegerField(verbose_name='Количество на точке')),
                ('change_data', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user_edited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено')),
                ('store', models.ForeignKey(default='Точка', on_delete=django.db.models.deletion.PROTECT, to='tph_system.store', verbose_name='Точка')),
            ],
            options={
                'verbose_name': 'Расходники на точке',
                'verbose_name_plural': 'Расходники на точке',
                'ordering': ['store', 'consumable'],
            },
        ),
        migrations.CreateModel(
            name='CashWithdrawn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('withdrawn', models.IntegerField(verbose_name='Сколько забрали наличными')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('date_upd', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user_edited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.staff', verbose_name='Сотрудник')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.store', verbose_name='Точка')),
            ],
            options={
                'verbose_name': 'Выдача зарплаты наличкой',
                'verbose_name_plural': 'Выдача зарплаты наличкой',
                'ordering': ['-date', 'store'],
            },
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('serial_num', models.CharField(blank=True, max_length=30, verbose_name='Серийный номер')),
                ('count', models.IntegerField(default=1, verbose_name='Количество на точке')),
                ('date_buy', models.DateField(verbose_name='Дата покупки')),
                ('warranty_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания гарантии')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.store', verbose_name='Точка')),
                ('user_edited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено')),
            ],
            options={
                'verbose_name': 'Фототехника',
                'verbose_name_plural': 'Фототехника',
                'ordering': ['store', 'name'],
            },
        ),
        migrations.AddField(
            model_name='refsandtips',
            name='title',
            field=models.CharField(blank=True, choices=[('Бигвол', 'Бигвол'), ('Лазерлэнд', 'Лазерлэнд')],
                                   max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='work_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Время работы'),
        ),
        migrations.AlterField(
            model_name='consumablesstore',
            name='count',
            field=models.DecimalField(decimal_places=1, max_digits=8, verbose_name='Количество на точке'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('staff', 'date')},
        ),
    ]
