# Generated by Django 5.1.4 on 2025-03-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='photo_count',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Кол-во фотографий'),
        ),
    ]
