# Generated by Django 5.1.4 on 2025-11-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
    ]
