# Generated by Django 5.1.4 on 2025-06-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='cnt_logs',
            field=models.TextField(blank=True, null=True, verbose_name='Лог расчета'),
        ),
    ]
