# Generated by Django 5.1.4 on 2025-02-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='dism_status',
            field=models.CharField(choices=[('Уволен', 'Уволен'), ('Работает', 'Работает')], default='Работает', max_length=30, verbose_name='Статус'),
        ),
    ]
