# Generated by Django 5.1.4 on 2025-06-01 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('cash_mrn', models.IntegerField(default=0, verbose_name='Наличные в начале дня')),
                ('cash_evn', models.IntegerField(default=0, verbose_name='Наличные в конце дня')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_upd', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.store', verbose_name='Точка')),
                ('user_edited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено')),
            ],
            options={
                'verbose_name': 'Наличные на точке',
                'verbose_name_plural': 'Наличные на точке',
                'ordering': ['-date', 'store'],
            },
        ),
    ]
