# Generated by Django 5.1.4 on 2025-12-03 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0002_alter_schedule_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkVacSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('staff_wrk_status', models.CharField(blank=True, choices=[('', ''), ('Работает', 'Работает'), ('Отпуск', 'Отпуск'), ('Отгул', 'Отгул')], default='', max_length=40, null=True, verbose_name='Рабочий статус')),
                ('time_availiable', models.CharField(blank=True, max_length=30, null=True, verbose_name='Временной период')),
                ('date_upd', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.staff', verbose_name='Сотрудник')),
                ('user_edited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено')),
            ],
            options={
                'verbose_name': 'График выходов и отпусков',
                'verbose_name_plural': 'График выходов и отпусков',
                'ordering': ['-date', 'staff'],
            },
        ),
    ]
