# Generated by Django 5.1.4 on 2025-07-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0002_salary_cnt_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='payment_type',
            field=models.CharField(choices=[('Оплата через парк', 'Оплата через парк'), ('Наличные', 'Наличные'), ('Карта', 'Карта'), ('Оплата по QR коду', 'Оплата по QR коду'), ('Перевод по номеру телефона', 'Перевод по номеру телефона'), ('Предоплаченный заказ', 'Предоплаченный заказ')], default='', max_length=40, verbose_name='Способ оплаты'),
        ),
    ]
