# Generated by Django 5.0.6 on 2024-05-11 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0002_consumables_paymenttype_positions_saletype_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='positions',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='saletype',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='store',
            name='short_name',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='CashWithdrawn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('withdrawn', models.IntegerField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tph_system.staff')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tph_system.store')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumablesStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('change_data', models.DateField()),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tph_system.consumables')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tph_system.store')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('salary_sum', models.DecimalField(decimal_places=2, max_digits=8)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tph_system.staff')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tph_system.store')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('sum', models.IntegerField()),
                ('photo_count', models.IntegerField()),
                ('cl_email', models.CharField(max_length=40)),
                ('cl_phone', models.CharField(max_length=12)),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tph_system.paymenttype')),
                ('sale_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tph_system.saletype')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tph_system.staff')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tph_system.store')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumablesSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('consumable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tph_system.consumables')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tph_system.sales')),
            ],
        ),
    ]
