# Generated by Django 5.1.4 on 2025-06-02 20:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0003_cashwithdrawn_week_beg_rec_store_store_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cashstore',
            constraint=models.UniqueConstraint(fields=('store', 'date'), name='unique_store_daily'),
        ),
    ]
