# Generated by Django 5.1.4 on 2025-11-03 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0003_alter_sales_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sale_type',
            field=models.CharField(choices=[('Email (фото)', 'Email (фото)'), ('Email (все)', 'Email (все)'), ('Вин. магн.', 'Вин. магн.'), ('Ср. магн.', 'Ср. магн.'), ('Бол. магн.', 'Бол. магн.'), ('Печать 10x15', 'Печать 10x15'), ('Печать 15x20', 'Печать 15x20'), ('Печать A4', 'Печать A4'), ('Заказной фотосет', 'Заказной фотосет'), ('Доп час к заказу', 'Доп час к заказу'), ('Исходники заказа', 'Исходники заказа'), ('Заказ выездной', 'Заказ выездной'), ('Заказная видеосъемка', 'Заказная видеосъемка')], default='', max_length=40, verbose_name='Тип продажи'),
        ),
        migrations.CreateModel(
            name='CheckReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('sum_cashbox', models.IntegerField(default=0, verbose_name='Касса')),
                ('check_status', models.CharField(choices=[('ОК', 'ОК'), ('Были ошибки', 'Были ошибки'), ('Не проверено', 'Не проверено')], default='Не проверено', max_length=50, verbose_name='Статус проверки')),
                ('comments', models.TextField(verbose_name='Подробности проверки')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.store', verbose_name='Точка')),
            ],
            options={
                'verbose_name': 'Отчеты',
                'verbose_name_plural': 'Отчеты',
                'ordering': ['-date', 'store'],
                'constraints': [models.UniqueConstraint(fields=('store', 'date'), name='unique_store_daily_reports')],
            },
        ),
    ]
