# Generated by Django 5.0.6 on 2024-05-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0003_alter_paymenttype_name_alter_positions_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='payment_type',
            field=models.CharField(default='Способ оплаты', max_length=40),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='position',
            field=models.CharField(default='Должность в смене', max_length=40),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_type',
            field=models.CharField(default='Тип продажи фото', max_length=40),
        ),
        migrations.AlterField(
            model_name='consumablessales',
            name='consumable',
            field=models.CharField(default='Название расходника', max_length=60),
        ),
        migrations.AlterField(
            model_name='consumablesstore',
            name='consumable',
            field=models.CharField(default='Название расходника', max_length=60),
        ),
        migrations.DeleteModel(
            name='PaymentType',
        ),
        migrations.DeleteModel(
            name='Positions',
        ),
        migrations.DeleteModel(
            name='SaleType',
        ),
    ]
