# Generated by Django 5.1.4 on 2025-12-03 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0003_workvacschedule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workvacschedule',
            unique_together={('staff', 'date')},
        ),
    ]
