# Generated by Django 5.1.4 on 2025-12-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0004_alter_workvacschedule_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workvacschedule',
            name='staff_wrk_status',
            field=models.CharField(blank=True, choices=[('', ''), ('Работает', 'Работает'), ('Отпуск', 'Отпуск'), ('Отгул', 'Отгул'), ('Больничный', 'Больничный')], default='', max_length=40, null=True, verbose_name='Рабочий статус'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('staff', 'date', 'store')},
        ),
    ]
