# Generated by Django 5.1.4 on 2025-11-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0004_alter_sales_sale_type_checkreports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkreports',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Подробности проверки'),
        ),
    ]
