# Generated by Django 5.0.6 on 2024-05-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0004_alter_sales_payment_type_alter_schedule_position_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consumables',
        ),
    ]
