# Generated by Django 5.1.4 on 2025-12-05 19:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0005_alter_workvacschedule_staff_wrk_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['date', 'staff'], name='tph_system__date_b7c88a_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['staff', 'date'], name='tph_system__staff_i_2f2943_idx'),
        ),
        migrations.AddIndex(
            model_name='workvacschedule',
            index=models.Index(fields=['date', 'staff'], name='tph_system__date_667191_idx'),
        ),
        migrations.AddIndex(
            model_name='workvacschedule',
            index=models.Index(fields=['staff', 'date'], name='tph_system__staff_i_b4a120_idx'),
        ),
    ]
