# Generated by Django 5.0.6 on 2024-05-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0006_alter_cashwithdrawn_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
