# Generated by Django 5.0.6 on 2024-06-05 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0007_alter_sales_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashwithdrawn',
            options={'ordering': ['date', 'store'], 'verbose_name': 'Выдача зарплаты наличкой', 'verbose_name_plural': 'Выдача зарплаты наличкой'},
        ),
        migrations.AlterModelOptions(
            name='consumablessales',
            options={'ordering': ['sale'], 'verbose_name': 'Потраченные расходники за продажу', 'verbose_name_plural': 'Потраченные расходники за продажу'},
        ),
        migrations.AlterModelOptions(
            name='consumablesstore',
            options={'ordering': ['store', 'consumable'], 'verbose_name': 'Расходники на точке', 'verbose_name_plural': 'Расходники на точке'},
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ['date', 'store'], 'verbose_name': 'Зарплаты сотрудников', 'verbose_name_plural': 'Зарплаты сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['store', 'date'], 'verbose_name': 'Продажи', 'verbose_name_plural': 'Продажи'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['date', 'store'], 'verbose_name': 'График сотрудников', 'verbose_name_plural': 'График сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['f_name', 'name'], 'verbose_name': 'Сотрудники', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name'], 'verbose_name': 'Точки', 'verbose_name_plural': 'Точки'},
        ),
        migrations.AddField(
            model_name='sales',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, editable=False, blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashwithdrawn',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.staff'),
        ),
        migrations.AlterField(
            model_name='cashwithdrawn',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.store'),
        ),
        migrations.AlterField(
            model_name='consumablessales',
            name='consumable',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='consumablessales',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.sales'),
        ),
        migrations.AlterField(
            model_name='consumablesstore',
            name='consumable',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='consumablesstore',
            name='store',
            field=models.ForeignKey(default='Точка', on_delete=django.db.models.deletion.PROTECT, to='tph_system.store'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.staff'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.store'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='cl_email',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='sales',
            name='cl_phone',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_type',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_type',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='sales',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.staff'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.store'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.staff'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.store'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_dism',
            field=models.DateField(blank=True, null=True),
        ),
    ]
