# Generated by Django 5.0.6 on 2024-06-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0009_tech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='warranty_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
