# Generated by Django 5.0.6 on 2024-06-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0010_alter_tech_warranty_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
