# Generated by Django 5.0.6 on 2024-08-07 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0011_tech_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['-date_created', 'store'], 'verbose_name': 'Продажи', 'verbose_name_plural': 'Продажи'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-date', 'store'], 'verbose_name': 'График сотрудников', 'verbose_name_plural': 'График сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['name', 'f_name'], 'verbose_name': 'Сотрудники', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AddField(
            model_name='staff',
            name='st_username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_type',
            field=models.CharField(choices=[('Наличные', 'Наличные'), ('Карта', 'Карта'), ('Оплата по QR коду', 'Оплата по QR коду'), ('Перевод по номеру телефона', 'Перевод по номеру телефона')], default='', max_length=40),
        ),
    ]
