# Generated by Django 5.0.6 on 2024-08-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0012_alter_sales_options_alter_schedule_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefsAndTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.TextField()),
                ('refs', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Инфо и ссылки',
                'verbose_name_plural': 'Инфо и ссылки',
                'ordering': ['-id'],
            },
        ),
    ]
