# Generated by Django 5.0.6 on 2024-09-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0015_sales_comment_sales_photographer'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumablesstore',
            name='cons_short',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_type',
            field=models.CharField(choices=[('Наличные', 'Наличные'), ('Карта', 'Карта'), ('Оплата по QR коду', 'Оплата по QR коду'), ('Перевод по номеру телефона', 'Перевод по номеру телефона'), ('Предоплаченный заказ', 'Предоплаченный заказ')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_type',
            field=models.CharField(choices=[('Email (фото)', 'Email (фото)'), ('Email (все)', 'Email (все)'), ('Вин. магн.', 'Вин. магн.'), ('Ср. магн.', 'Ср. магн.'), ('Бол. магн.', 'Бол. магн.'), ('Печать 10x15', 'Печать 10x15'), ('Печать 15x20', 'Печать 15x20'), ('Печать A4', 'Печать A4'), ('Заказной фотосет', 'Заказной фотосет')], default='', max_length=40),
        ),
    ]
