# Generated by Django 5.0.6 on 2024-09-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0016_consumablesstore_cons_short_alter_sales_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumablesstore',
            name='cons_short',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
