# Generated by Django 5.0.6 on 2024-09-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0017_alter_consumablesstore_cons_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_f_name', models.CharField(max_length=100)),
                ('param', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=30)),
                ('date_upd', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
                'ordering': ['param'],
            },
        ),
        migrations.AddField(
            model_name='sales',
            name='date_upd',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='consumablesstore',
            name='change_data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
