# Generated by Django 5.0.6 on 2024-10-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0019_alter_settings_param_alter_settings_param_f_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ['-date', 'staff'], 'verbose_name': 'Зарплаты сотрудников', 'verbose_name_plural': 'Зарплаты сотрудников'},
        ),
        migrations.AddField(
            model_name='salary',
            name='cash_box',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_type',
            field=models.CharField(choices=[('Email (фото)', 'Email (фото)'), ('Email (все)', 'Email (все)'), ('Вин. магн.', 'Вин. магн.'), ('Ср. магн.', 'Ср. магн.'), ('Бол. магн.', 'Бол. магн.'), ('Печать 10x15', 'Печать 10x15'), ('Печать 15x20', 'Печать 15x20'), ('Печать A4', 'Печать A4'), ('Заказной фотосет', 'Заказной фотосет'), ('Заказ выездной', 'Заказ выездной')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='position',
            field=models.CharField(choices=[('Администратор', 'Администратор'), ('Фотограф', 'Фотограф'), ('Универсальный фотограф', 'Универсальный фотограф')], default='Должность в смене', max_length=40),
        ),
    ]
