# Generated by Django 5.0.6 on 2024-10-31 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0020_alter_salary_options_salary_cash_box_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImplErrors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=50)),
                ('error_message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ошибки выполнения',
                'verbose_name_plural': 'Ошибки выполнения',
                'ordering': ['id', 'error_type'],
            },
        ),
        migrations.AlterModelOptions(
            name='cashwithdrawn',
            options={'ordering': ['-date', 'store'], 'verbose_name': 'Выдача зарплаты наличкой', 'verbose_name_plural': 'Выдача зарплаты наличкой'},
        ),
        migrations.CreateModel(
            name='SalaryWeekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_begin', models.DateField()),
                ('week_end', models.DateField()),
                ('salary_sum', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cash_withdrawn', models.IntegerField()),
                ('to_pay', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paid_out', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='', max_length=10)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.staff')),
            ],
            options={
                'verbose_name': 'Зарплаты за неделю',
                'verbose_name_plural': 'Зарплаты за неделю',
                'ordering': ['-week_begin', 'staff'],
            },
        ),
    ]
