# Generated by Django 5.0.6 on 2024-10-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0021_implerrors_alter_cashwithdrawn_options_salaryweekly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryweekly',
            name='paid_out',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=10),
        ),
    ]
