# Generated by Django 5.0.6 on 2024-11-02 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
       #  ('schedule', '0014_use_autofields_for_pk'),
        ('tph_system', '0022_alter_salaryweekly_paid_out'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='implerrors',
            options={'ordering': ['-id', 'error_type'], 'verbose_name': 'Ошибки выполнения', 'verbose_name_plural': 'Ошибки выполнения'},
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('event_type', models.CharField(choices=[('vacation', 'Отпуск'), ('holiday', 'Праздничный день'), ('school_break', 'Школьные каникулы')], max_length=20, verbose_name='Тип события')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('employee', models.ForeignKey(blank=True, help_text='Заполняется только для отпусков', null=True, on_delete=django.db.models.deletion.CASCADE, to='tph_system.staff', verbose_name='Сотрудник')),
                #('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.event')),
            ],
            options={
                'verbose_name': 'Календарь событий',
                'verbose_name_plural': 'Календарь событий',
            },
        ),
    ]
