# Generated by Django 5.0.6 on 2024-11-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0023_alter_implerrors_options_calendarevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImplEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('event_message', models.TextField()),
                ('status', models.CharField(choices=[('Системная ошибка', 'Системная ошибка'), ('Бизнес ошибка', 'Бизнес ошибка'), ('Успешно', 'Успешно')], max_length=50)),
                ('solved', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Системные события',
                'verbose_name_plural': 'Системные события',
                'ordering': ['-id', 'event_type'],
            },
        ),
        migrations.DeleteModel(
            name='ImplErrors',
        ),
    ]
