# Generated by Django 5.0.6 on 2024-11-04 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0024_implevents_delete_implerrors'),
    ]

    operations = [
        migrations.AddField(
            model_name='implevents',
            name='user_edited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tph_system.staff'),
        ),
    ]
