# Generated by Django 5.0.6 on 2024-11-05 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0026_cashwithdrawn_date_upd_cashwithdrawn_user_edited_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ['-date', 'staff'], 'verbose_name': 'Зарплаты', 'verbose_name_plural': 'Зарплаты'},
        ),
        migrations.AlterField(
            model_name='cashwithdrawn',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='cashwithdrawn',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='cashwithdrawn',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.staff', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='cashwithdrawn',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.store', verbose_name='Точка'),
        ),
        migrations.AlterField(
            model_name='cashwithdrawn',
            name='user_edited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено'),
        ),
        migrations.AlterField(
            model_name='cashwithdrawn',
            name='withdrawn',
            field=models.IntegerField(verbose_name='Сколько забрали наличными'),
        ),
        migrations.AlterField(
            model_name='consumablesstore',
            name='change_data',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='consumablesstore',
            name='cons_short',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Функциональное наименование (не изменять)'),
        ),
        migrations.AlterField(
            model_name='consumablesstore',
            name='consumable',
            field=models.CharField(max_length=60, verbose_name='Расходник'),
        ),
        migrations.AlterField(
            model_name='consumablesstore',
            name='count',
            field=models.IntegerField(verbose_name='Количество на точке'),
        ),
        migrations.AlterField(
            model_name='consumablesstore',
            name='store',
            field=models.ForeignKey(default='Точка', on_delete=django.db.models.deletion.PROTECT, to='tph_system.store', verbose_name='Точка'),
        ),
        migrations.AlterField(
            model_name='consumablesstore',
            name='user_edited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено'),
        ),
        migrations.AlterField(
            model_name='implevents',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='implevents',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='implevents',
            name='event_message',
            field=models.TextField(verbose_name='Текст события'),
        ),
        migrations.AlterField(
            model_name='implevents',
            name='event_type',
            field=models.CharField(max_length=50, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='implevents',
            name='solved',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=10, verbose_name='Решено'),
        ),
        migrations.AlterField(
            model_name='implevents',
            name='status',
            field=models.CharField(choices=[('Системная ошибка', 'Системная ошибка'), ('Бизнес ошибка', 'Бизнес ошибка'), ('Успешно', 'Успешно')], max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='implevents',
            name='user_edited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено'),
        ),
        migrations.AlterField(
            model_name='refsandtips',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='refsandtips',
            name='refs',
            field=models.CharField(max_length=200, verbose_name='Ссылки'),
        ),
        migrations.AlterField(
            model_name='refsandtips',
            name='tip',
            field=models.TextField(verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='refsandtips',
            name='user_edited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='cash_box',
            field=models.IntegerField(default=0, verbose_name='Касса за день'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary_sum',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Зарплата за день'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.staff', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.store', verbose_name='Точка'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='user_edited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено'),
        ),
        migrations.AlterField(
            model_name='salaryweekly',
            name='cash_withdrawn',
            field=models.IntegerField(verbose_name='Забрали наличными за неделю'),
        ),
        migrations.AlterField(
            model_name='salaryweekly',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='salaryweekly',
            name='paid_out',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=10, verbose_name='Выплачено'),
        ),
        migrations.AlterField(
            model_name='salaryweekly',
            name='salary_sum',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Зарплата за неделю'),
        ),
        migrations.AlterField(
            model_name='salaryweekly',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.staff', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='salaryweekly',
            name='to_pay',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Осталось выплатить'),
        ),
        migrations.AlterField(
            model_name='salaryweekly',
            name='user_edited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено'),
        ),
        migrations.AlterField(
            model_name='salaryweekly',
            name='week_begin',
            field=models.DateField(verbose_name='Начало периода'),
        ),
        migrations.AlterField(
            model_name='salaryweekly',
            name='week_end',
            field=models.DateField(verbose_name='Конец периода'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='cl_email',
            field=models.CharField(blank=True, max_length=40, verbose_name='Email клиента'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='cl_phone',
            field=models.CharField(blank=True, max_length=12, verbose_name='Телефон клиента'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_type',
            field=models.CharField(choices=[('Наличные', 'Наличные'), ('Карта', 'Карта'), ('Оплата по QR коду', 'Оплата по QR коду'), ('Перевод по номеру телефона', 'Перевод по номеру телефона'), ('Предоплаченный заказ', 'Предоплаченный заказ')], default='', max_length=40, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='photo_count',
            field=models.IntegerField(verbose_name='Кол-во фотографий'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='photographer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='sale_photographer', to='tph_system.staff', verbose_name='Фотограф'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_type',
            field=models.CharField(choices=[('Email (фото)', 'Email (фото)'), ('Email (все)', 'Email (все)'), ('Вин. магн.', 'Вин. магн.'), ('Ср. магн.', 'Ср. магн.'), ('Бол. магн.', 'Бол. магн.'), ('Печать 10x15', 'Печать 10x15'), ('Печать 15x20', 'Печать 15x20'), ('Печать A4', 'Печать A4'), ('Заказной фотосет', 'Заказной фотосет'), ('Заказ выездной', 'Заказ выездной')], default='', max_length=40, verbose_name='Тип продажи'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.staff', verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.store', verbose_name='Точка'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sum',
            field=models.IntegerField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='user_edited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='position',
            field=models.CharField(choices=[('Роль не указана', 'Роль не указана'), ('Администратор', 'Администратор'), ('Фотограф', 'Фотограф'), ('Универсальный фотограф', 'Универсальный фотограф')], default='Роль не указана', max_length=40, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.staff', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.store', verbose_name='Точка'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user_edited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='param',
            field=models.CharField(max_length=50, verbose_name='Параметр'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='param_f_name',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='user_edited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='value',
            field=models.CharField(max_length=30, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_dism',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_empl',
            field=models.DateField(verbose_name='Дата найма'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='f_name',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='o_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='st_username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Учетная запись'),
        ),
        migrations.AlterField(
            model_name='store',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='store',
            name='short_name',
            field=models.CharField(max_length=20, verbose_name='Функциональное название (не изменять)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='user_edited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Количество на точке'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='date_buy',
            field=models.DateField(verbose_name='Дата покупки'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='date_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='serial_num',
            field=models.CharField(blank=True, max_length=30, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.store', verbose_name='Точка'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='user_edited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='warranty_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания гарантии'),
        ),
    ]
