# Generated by Django 5.0.6 on 2024-11-07 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0028_alter_implevents_solved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='user_edited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_user_edited', to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено'),
        ),
        migrations.AlterField(
            model_name='implevents',
            name='status',
            field=models.CharField(choices=[('Системная ошибка', 'Системная ошибка'), ('Бизнес ошибка', 'Бизнес ошибка'), ('Успешно', 'Успешно'), ('Удаление записи', 'Удаление записи')], max_length=50, verbose_name='Статус'),
        ),
    ]
