# Generated by Django 5.0.6 on 2024-11-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0029_staff_user_edited_alter_implevents_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_box', models.IntegerField(verbose_name='Касса')),
            ],
        ),
        migrations.AddField(
            model_name='salaryweekly',
            name='cash_box_week',
            field=models.IntegerField(default=0, verbose_name='Касса за неделю'),
        ),
    ]
