# Generated by Django 5.0.6 on 2024-11-13 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0030_finstats_salaryweekly_cash_box_week'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinStatsMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Отчетный месяц')),
                ('revenue', models.IntegerField(verbose_name='Выручка (Кассы)')),
                ('salaries', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Зарплаты')),
                ('expenses', models.IntegerField(verbose_name='Расходы')),
                ('profit', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Прибыль')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user_edited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено')),
            ],
        ),
        migrations.CreateModel(
            name='FinStatsStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Отчетный месяц')),
                ('cash_box', models.IntegerField(verbose_name='Касса')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Зарплата')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tph_system.staff', verbose_name='Сотрудник')),
                ('user_edited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем было изменено')),
            ],
        ),
        migrations.DeleteModel(
            name='FinStats',
        ),
    ]
