# Generated by Django 5.1.4 on 2024-12-08 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tph_system', '0033_cashwithdrawn_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finstatsmonth',
            options={'ordering': ['-date'], 'verbose_name': 'Финансы - компания', 'verbose_name_plural': 'Финансы - компания'},
        ),
        migrations.AlterModelOptions(
            name='finstatsstaff',
            options={'ordering': ['-date', 'staff'], 'verbose_name': 'Финансы - сотрудники', 'verbose_name_plural': 'Финансы - сотрудники'},
        ),
        migrations.DeleteModel(
            name='CalendarEvent',
        ),
    ]
